'use client';
import { useState } from 'react';
import { EditorContent, useEditor } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import { plainDocument, safeLink, type DiaryEntry } from './diary';
export default function Writer({entry,onChange,status}:{entry:DiaryEntry;onChange:(value:DiaryEntry)=>void;status:string}){
 const [linkOpen,setLinkOpen]=useState(false),[url,setUrl]=useState(''),[linkError,setLinkError]=useState('');
 const editor=useEditor({extensions:[StarterKit.configure({heading:{levels:[2,3]},link:{openOnClick:false,protocols:['https','http','mailto']}})],content:entry.document||plainDocument(entry.body),immediatelyRender:false,shouldRerenderOnTransaction:true,editorProps:{attributes:{'aria-label':'日記編輯器','role':'textbox','aria-multiline':'true',class:'word-editor'}},onUpdate:({editor})=>onChange({...entry,body:editor.getText({blockSeparator:'\n'}),document:editor.getJSON()})});
 if(!editor)return <p className="writer-loading">正在打開手帖…</p>;
 const actions=[{label:'粗體',text:'B',active:editor.isActive('bold'),run:()=>editor.chain().focus().toggleBold().run()},{label:'斜體',text:'I',active:editor.isActive('italic'),run:()=>editor.chain().focus().toggleItalic().run()},{label:'底線',text:'U',active:editor.isActive('underline'),run:()=>editor.chain().focus().toggleUnderline().run()},{label:'小標題',text:'H₂',active:editor.isActive('heading',{level:2}),run:()=>editor.chain().focus().toggleHeading({level:2}).run()},{label:'項目清單',text:'• 清單',active:editor.isActive('bulletList'),run:()=>editor.chain().focus().toggleBulletList().run()},{label:'編號清單',text:'1. 清單',active:editor.isActive('orderedList'),run:()=>editor.chain().focus().toggleOrderedList().run()},{label:'引用',text:'❝',active:editor.isActive('blockquote'),run:()=>editor.chain().focus().toggleBlockquote().run()}];
 return <section className="writer"><header className="writer-header"><div><h1>{entry.date}</h1><span>{entry.day}</span></div><output className="save-indicator">{status}</output></header>
 <div className="format-bar" role="toolbar" aria-label="文字格式">{actions.map(a=><button key={a.label} type="button" title={a.label} aria-label={a.label} aria-pressed={a.active} onMouseDown={e=>e.preventDefault()} onClick={a.run}>{a.text}</button>)}<button type="button" aria-label="插入或修改連結" onMouseDown={e=>e.preventDefault()} onClick={()=>{setUrl(editor.getAttributes('link').href||'');setLinkError('');setLinkOpen(!linkOpen);}}>連結</button><button type="button" aria-label="復原" disabled={!editor.can().undo()} onClick={()=>editor.chain().focus().undo().run()}>↶</button><button type="button" aria-label="重做" disabled={!editor.can().redo()} onClick={()=>editor.chain().focus().redo().run()}>↷</button></div>
 {linkOpen&&<form className="link-form" onSubmit={e=>{e.preventDefault();const href=safeLink(url.trim());if(!href){setLinkError('請輸入完整的 https://、http:// 或 mailto: 連結。');return;}if(editor.state.selection.empty&&!editor.isActive('link'))editor.chain().focus().insertContent({type:'text',text:href,marks:[{type:'link',attrs:{href}}]}).run();else editor.chain().focus().extendMarkRange('link').setLink({href}).run();setLinkOpen(false);}}><label>連結網址<input type="text" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><button>套用</button><button type="button" onClick={()=>{editor.chain().focus().extendMarkRange('link').unsetLink().run();setLinkOpen(false);}}>移除連結</button><button type="button" onClick={()=>setLinkOpen(false)}>取消</button>{linkError&&<p role="alert">{linkError}</p>}</form>}
 <EditorContent editor={editor}/><footer className="writer-footer"><span>{Array.from(editor.getText()).length} 字</span><span>Enter 分段 · Shift＋Enter 換行</span></footer><p className="writing-hint">停止輸入後會同步至 Google 試算表。<br/>請等到顯示「已存入」再離開；連線失敗時可下載草稿備份。</p>
 </section>;
}
